version: "4"

services:
  db-test:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: "db_owner"
      POSTGRES_PASSWORD: "testing"
      POSTGRES_DB: "storage"
    volumes:
      - ./postgresql.conf:/etc/postgresql.conf
      - db-data-test:/var/lib/postgresql/data
      - ./load_init_testing.sql:/docker-entrypoint-initdb.d/load_init_testing.sql
    restart: unless-stopped
    networks:
      - full_stack

volumes:
  db-data-test: {}
  cache:
    driver: local

networks:
  full_stack:
    name: full_stack
  shared:
    external: true
